import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import AppSidebar from '@/components/app-sidebar'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
})

export const metadata = {
    title: 'SkillMatch',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
    return (
        <html lang="pt-BR">
            <body>
                <SidebarProvider>
                    <AppSidebar />
                    <main className="flex-1">
                        <SidebarTrigger />
                        {children}
                    </main>
                </SidebarProvider>
            </body>
        </html>
    )
}
